# Basic Azure Pipeline for building job and push to Azure ACR

trigger:
- master

variables:
  project_name: ttd
  job_name: onboardingdemojob
  job_version: 0.1 
  commandline_path: C:/studio # CHANGE WITH YOUR OWN PATH
  
  JAVA_HOME_8_X64: C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.262-3
  
jobs:

- job: checkout
  pool: 'default' # ADAPT IF YOU HAVE A AGENT POOL NAME
  displayName: 'Git Checkout'
  continueOnError: false
  steps:
  - checkout: self
    clean: true

- job: build
  pool: 'Default'
  dependsOn: checkout
  displayName: 'Job Build & Publish to ACR'
  continueOnError: false
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'poms/pom.xml' 
      goals: 'package'
      options: '--settings $(commandline_path)/configuration/maven_user_settings.xml -U -DaltDeploymentRepository=snapshots::default::http://prdlnxtara:8081/repository/snapshots/  -e -pl jobs/process/demo/$(job_name)_$(job_version) -am '
      publishJUnitResults: false 
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkDirectory: 'C:/Program Files/RedHat/java-1.8.0-openjdk-1.8.0.262-3/bin/java'
      mavenVersionOption: path
      mavenDirectory: 'C:\apache-maven-3.6.3-bin\apache-maven-3.6.3'
      mavenOptions: '-Dgeneration.type=local -Dproduct.path=$(commandline_path) -DaltDeploymentRepository=snapshots::default::http://prdlnxtara:8081/repository/snapshots/ -Xmx3096m -Xmx1024m'
      sonarQubeRunAnalysis: false 
      